### ISSUE TITLE
Missing project.pbxproj files for both xcode projects ?

### ISSUE THREAD

**Issue by ghost** [JacopoMangiavacchi/HeightWidthCoreMLKerasTest#1]
XCode (9.2) cannot open the .xcodeproj files: 'Project /Users/adev/src/HeightWeightCoreMLKerasTest/iOS Project/HeightWeightCoreMLKerasTest.xcodeproj cannot be opened because it is missing its project.pbxproj file.'

**Comment by fozoglu** [comment]
I have same problem. Some ios project files are missing.

**Comment by freemansion** [comment]
confirming, having the same issue. Anyone got luck in fixing it?

**Comment by freemansion** [comment]
I think @JacopoMangiavacchi could just forgot to commit `.pbxproj` somehow.

**Comment by freemansion** [comment]
made a PR fixing that #2

**Comment by JacopoMangiavacchi** [comment]
Thank you @freemansion and sorry for the delay

**Comment by freemansion** [comment]
@JacopoMangiavacchi thank you for the great article and example!
